# Generated by Django 4.2 on 2023-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendskills',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frontendskills',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
