# Generated by Django 4.2 on 2023-04-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0002_alter_backendskills_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbody',
            name='post',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='projectBody',
        ),
    ]
