# Generated by Django 4.2 on 2023-04-12 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0005_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95675f63-8805-4d11-a999-c59b674b51c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
