# Generated by Django 4.2 on 2023-04-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0007_alter_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbody',
            old_name='bodyBody',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='projectbody',
            old_name='bodyTitle',
            new_name='title',
        ),
    ]
