# Generated by Django 4.2 on 2023-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0008_rename_bodybody_projectbody_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbody',
            name='Image',
            field=models.ImageField(blank=True, upload_to='project/pk'),
        ),
    ]
