# Generated by Django 4.2 on 2023-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0010_category_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbody',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='projectbody',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
