# Generated by Django 4.2 on 2023-04-16 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0011_alter_projectbody_options_projectbody_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c430b66-3cc1-4d30-aad6-d915d3cddd4f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
