# Generated by Django 4.2 on 2023-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0022_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
