# Generated by Django 4.2 on 2023-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0039_alter_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbody',
            old_name='Image',
            new_name='image',
        ),
    ]
