# Generated by Django 4.2 on 2023-04-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0040_rename_image_projectbody_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
