# Generated by Django 4.2 on 2023-04-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0042_alter_project_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
    ]
