# Generated by Django 4.2 on 2023-04-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basePortfolio', '0043_delete_message_alter_project_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backEndSkills',
        ),
        migrations.DeleteModel(
            name='frameWorks',
        ),
        migrations.DeleteModel(
            name='frontEndSkills',
        ),
    ]
