# Generated by Django 4.2 on 2023-04-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0002_backendskills_frameworksskills_frontendskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontEndSkillsForm',
            fields=[
                ('frontendskills_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminManage.frontendskills')),
            ],
            bases=('adminManage.frontendskills',),
        ),
    ]
