# Generated by Django 4.2 on 2023-04-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0003_frontendskillsform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frontEndSkillsForm',
        ),
    ]
