# Generated by Django 4.2 on 2023-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0010_alter_backendskills_id_alter_frameworksskills_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, upload_to='profile')),
            ],
        ),
    ]
