# Generated by Django 4.2 on 2023-06-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManage', '0011_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profileImage',
            new_name='image',
        ),
    ]
